name: CloneTwitter
options:
  bundleIdPrefix: com.pan
  deploymentTarget:
    iOS: 17.0
  xcodeVersion: "15.1"
  generateEmptyDirectories: true
  createIntermediateGroups: true

targets:
  CloneTwitter:
    type: application
    platform: iOS
    sources: [Sources]
    dependencies:
      - package: Inject
    settings:
      base:
        SWIFT_VERSION: 5.9
        ENABLE_TESTABILITY: YES
        GENERATE_INFOPLIST_FILE: YES
        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: 1
        INFOPLIST_KEY_CFBundleDisplayName: "CloneTwitter"
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: UIInterfaceOrientationPortrait
        PRODUCT_BUNDLE_IDENTIFIER: com.pan.clonetwitter
        OTHER_LDFLAGS[config=Debug][sdk=iphonesimulator*]: $(inherited) -Xlinker -interposable

packages:
  Inject:
    url: https://github.com/krzysztofzablocki/Inject.git
    from: 1.2.4
